[package]
name = "sovereign_ledger-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
sovereign_ledger = { path = ".." }

[[bin]]
name = "verify_proofs"
path = "fuzz_targets/verify_proofs.rs"
test = false
doc = false

[[bin]]
name = "parse_event"
path = "fuzz_targets/parse_event.rs"
test = false
doc = false
